config/routes.rb
Rails.application.routes.draw do
  resources :jobs, only: [:index]
  post '/jobs', to: 'jobs#index'

  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobs_query.rb
class JobsQuery
  attr_reader :params, :page_number, :companies, :levels, :categories

  def initialize(params = {})
    @params = params
    @page_number = extract_page_number_from_params
    @companies = extract_array_from_params('companies')
    @levels = extract_array_from_params('levels')
    @categories = extract_array_from_params('categories')
  end

  # This method is needed to conform with the API that Rails' form_for helper
  # method expects.
  def model_name
    OpenStruct.new(param_key: 'jobs_query')
  end

  # This method is needed to conform with the API that Rails' form_for helper
  # method expects.
  def to_key
  end

  private def extract_page_number_from_params
    page_number = params['page_number']
    page_number = default_page_number if page_number.blank?

    page_number
  end

  private def default_page_number
    1
  end

  private def extract_array_from_params(key)
    params.fetch(key, []).reject(&:blank?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs_query = JobsQuery.new(params.fetch(:jobs_query, {}))
    query_executor = Jobs::QueryExecutor.new(@jobs_query)
    @query_response = query_executor.execute
    status = @query_response.status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def level_options(selected_options)
    option_names = extract_option_names('level.yml')
    options_for_select(option_names, selected_options)
  end

  def category_options(selected_options)
    option_names = extract_option_names('category.yml')
    options_for_select(option_names, selected_options)
  end

  private def extract_option_names(filename)
    config_file_path = File.join(search_options_config_directory, filename)
    config_file = File.open(config_file_path)
    YAML.load(config_file.read)
  end

  private def search_options_config_directory
    Rails.root.join('config', 'search_options')
  end
end

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<div class="ui segment">
  <%= form_for @jobs_query, url: jobs_path, html: { class: "ui form" } do |f| %>
    <%#= f.label :companies, "Company" %>
    <%#= f.select :companies, [], {}, multiple: true %>

    <div class="fields">
      <div class="field">
        <%= f.label :levels, "Level" %>
        <%= f.select :levels, level_options(@jobs_query.levels), {}, multiple: true, class: "ui dropdown" %>
      </div>

      <div class="field">
        <%= f.label :categories, "Category" %>
        <%= f.select :categories, category_options(@jobs_query.categories), {}, multiple: true, class: "ui dropdown" %>
      </div>

      <div class="field">
        <%= f.label :page_number, 'Page' %>
        <%= f.number_field :page_number, min: 1, step: 1 %>
      </div>
    </div>
    <%= f.submit "Search", class: "ui button" %>
  <% end %>
</div>

<% if @query_response.results.any? %>
  <div>Showing page <%= @query_response.page + 1%> of <%= @query_response.page_count %>.</div>

  <table class="ui table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Company</th>
        <th>Levels</th>
        <th>Categories</th>
      </tr>
    </thead>
    <!-- TODO: Implement a ResultPresenter that encapsulates presentational
      logic for converting the json result data into the text to be rendered.
    -->
    <% @query_response.results.each do |result| %>
      <tr>
        <td>
          <%= result['name'] %>
        </td>
        <td>
          <%= result['company']['name'] %>
        </td>
        <td>
          <%= result['levels'].map { |level| level['name'] }.join(', ') %>
        </td>
        <td>
          <%= result['categories'].map { |category| category['name'] }.join(', ') %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="ui negative message">
    <i class="warning sign icon"></i>
    An error has occurred and the search results could not be retrieved:
    <%= @query_response.error %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheMuseOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>